/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laptop.gltf --transform
Author: hellfa (https://sketchfab.com/hellfa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-d55ef30e28b1455bad46e0beeb85bfc6
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.12, 40.25, -51.77]} rotation={[-0.55, 0, 0]} scale={[4.27, 5.13, 1]}>
        <mesh geometry={nodes['klapa_Material_#41_0'].geometry} material={materials.Material_41} position={[-11.88, -5.34, 0.11]} />
      </group>
      <mesh geometry={nodes['podstawa_Material_#28_0'].geometry} material={materials.Material_28} position={[-50.57, 1.53, 47.85]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.27, 5.13, 1]} />
      <mesh geometry={nodes['Sphere002_Material_#42_0'].geometry} material={materials.Material_42} position={[61.86, 0.04, 62.74]} rotation={[Math.PI / 2, 0, 0]} scale={[0.93, 0.93, 0.28]} />
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
